AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Include:
    - 'lib/**/*'
  Exclude:
    - 'spec/**/*'
    - 'vendor/**/*'

Style/EmptyCaseCondition:
  Enabled: false

inherit_from: .rubocop_todo.yml
